services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite_app
    ports:
      - "9000:80"
      - "5174:5174"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  mysql:
    image: mysql:8.0
    container_name: vite_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trackspending
    ports:
      - "3308:3306"
    volumes:
      - trackspending_frontback_laravel11_dbdata:/var/lib/mysql

volumes:
  trackspending_frontback_laravel11_dbdata:
    external: true